language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

branches:
    except:
        - "release/cpan"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # gotta love failing pod tests blowing everything up...
   - cpanm -q TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }

install:
   # not so much install our package as all its prereqs
   - export HARNESS_SUBCLASS=TAP::Harness::Restricted
   - cpanm --installdeps .

script:
   - export DZSIGN=archive
   - unset HARNESS_SUBCLASS
   #- dzil test --release --author
   - prove -lr t/
