language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

env:
    matrix:
        - TARGET_LOCALE=en_US.UTF-8     NEW_LOCALE_PKGS=''
        - TARGET_LOCALE=ru_RU.UTF-8     NEW_LOCALE_PKGS='language-pack-ru'
        - TARGET_LOCALE=C               NEW_LOCALE_PKGS=''
        - TARGET_LOCALE=POSIX           NEW_LOCALE_PKGS=''
        - TARGET_LOCALE=de_DE.ISO8859-1 NEW_LOCALE_PKGS='language-pack-de'

before_install:
    - locale -a
    #- if [ -n "$NEW_LOCALE_PKGS" ] ; then sudo apt-get install $NEW_LOCALE_PKGS ; fi
    #- sudo dpkg-reconfigure locales
    - sudo locale-gen "$TARGET_LOCALE"
    #- export LC_ALL="$TARGET_LOCALE" LC_CTYPE="$TARGET_LOCALE" LANG="$TARGET_LOCALE"
    - export LANG="$TARGET_LOCALE" LC_MESSAGES="POSIX"

    # gotta love failing pod tests blowing everything up...
    - cpanm -q TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }

install:
    # not so much install our package as all its prereqs
    - export HARNESS_SUBCLASS=TAP::Harness::Restricted
    - cpanm --installdeps .

script:
    - unset HARNESS_SUBCLASS
    - prove -lr t/
